import {
  sourcePreflightInspectFields,
  withDirectoryRouteInspectFields,
} from './guidance-inspect-fields.js';
import {
  OUTPUT_AUDIT_DETAIL_INSPECT_FIELDS,
  OUTPUT_AUDIT_SUMMARY_INSPECT_FIELDS,
} from './output-audit-criteria.js';

export function buildRecommendedWorkflowPlan(workflow) {
  const auditStep = {
    id: 'audit-output',
    templateId: 'output-audit-compact',
    required: true,
    writesFiles: false,
    sourceDestructive: false,
    goal: 'Audit the generated output directory before reporting completion.',
    inspectFields: [...OUTPUT_AUDIT_SUMMARY_INSPECT_FIELDS],
    successCriteria: 'outputRoleDecision.auditAppliesToThisDirectory is not false, outputStructureDecision.status is pass, auditStatus is pass, auditPassed is true, structureSummary.conforms is true, maxFilesHit is false, and inspectionWarnings contain no action-required structure or truncation issues.',
  };
  const plans = {
    overview: {
      id: 'safe-agent-batch-workflow',
      summary: 'Default AI-agent path for an unfamiliar font directory: diagnose, preflight, resolve layout ambiguity, preview batch output, write only after review, then audit output.',
      orderedSteps: [
        {
          id: 'runtime-check',
          templateId: 'runtime-diagnostic',
          required: false,
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Confirm the workspace, Node runtime, package versions, and WASM runtime are usable when setup is uncertain.',
          inspectFields: ['ok', 'recommendedActions', 'workspace', 'wasm', 'cnFontSplit'],
          successCriteria: 'ok is true, or every recommendedActions item has been handled.',
        },
        {
          id: 'source-preflight',
          templateId: 'source-preflight-compact',
          required: true,
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Count supported fonts and ignored non-font files without writing output.',
          inspectFields: sourcePreflightInspectFields(['invalidFontCount']),
          successCriteria: 'maxFilesHit is false, or the caller intentionally accepts a bounded summary.',
        },
        {
          id: 'layout-decision',
          templateId: 'directory-mismatch-plan',
          required: 'when-layout-is-flat-mixed-unfamiliar-or-user-wants-staging',
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Use the organizer dry-run to decide whether direct batch splitting is safe or whether a copy-only staging directory is useful.',
          inspectFields: withDirectoryRouteInspectFields(['sourceSafetyDecision', 'safetySummary', 'batchPolicySummary', 'layout']),
          successCriteria: 'The desired grouping is clear and any organizationWarnings have been reviewed.',
        },
        {
          id: 'batch-preview',
          templateId: 'batch-dry-run-preview',
          required: true,
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Preview dedupe, naming, skip checks, warnings, and planned output paths before writing.',
          inspectFields: ['sourceSafetyDecision', 'safetySummary', 'batchPolicySummary', 'dryRun', 'batchDecision', 'planned', 'batchWarnings', 'maxFilesHit', 'dedupeDecisionSummary', 'skippedDuplicates', 'errorCount', 'errors'],
          successCriteria: 'dryRun is true, sourceDestructive is false, maxFilesHit is false, and planned paths/warnings are acceptable.',
        },
        {
          id: 'reviewed-write',
          templateId: 'batch-process-reviewed-plan',
          required: 'after-preview-review',
          writesFiles: true,
          sourceDestructive: false,
          goal: 'Write split output only after the preview has been reviewed.',
          inspectFields: ['sourceSafetyDecision', 'safetySummary', 'batchPolicySummary', 'batchDecision', 'batchWarnings', 'dedupeDecisionSummary', 'errorCount', 'errors', 'recommendedNextActions'],
          successCriteria: 'errorCount is zero and the response recommends or allows output audit.',
        },
        auditStep,
      ],
      decisionPoints: [
        {
          id: 'staging-needed',
          when: 'The user wants a cleaner source staging directory, or the source layout is too ambiguous for direct grouping.',
          useTemplateId: 'copy-organized-staging',
          inspectFields: withDirectoryRouteInspectFields(['sourceSafetyDecision', 'safetySummary', 'batchPolicySummary', 'copiedCount', 'organizationManifestPath']),
          nextInput: 'Use the organizer outputDir as split_font_batch inputDir only after reviewing warnings.',
          successCriteria: 'The copy plan remains sourceDestructive false and copy-only, with copiedCount and organizationWarnings matching the reviewed plan.',
        },
        {
          id: 'direct-batch-ok',
          when: 'The source layout already matches the desired grouping.',
          useTemplateId: 'batch-dry-run-preview',
          inspectFields: ['sourceSafetyDecision', 'safetySummary', 'batchDecision', 'planned', 'batchWarnings', 'unsupportedFileDecision', 'unsupportedFileSummary'],
          nextInput: 'Use the original inputDir for split_font_batch.',
          successCriteria: 'The direct batch preview remains dryRun true and sourceDestructive false, with planned grouping and warnings acceptable for the original inputDir.',
        },
      ],
    },
    single: {
      id: 'single-font-workflow',
      summary: 'Process one known font path, then interpret resultType/outputMode instead of treating ok:true as normal subset proof.',
      orderedSteps: [
        {
          id: 'runtime-check',
          templateId: 'runtime-diagnostic',
          required: false,
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Check setup when the workspace or runtime is uncertain.',
          inspectFields: ['ok', 'recommendedActions', 'workspace', 'wasm'],
          successCriteria: 'ok is true, or every recommendedActions item has been handled.',
        },
        {
          id: 'split-known-font',
          tool: 'split_font',
          required: true,
          writesFiles: true,
          sourceDestructive: false,
          goal: 'Process the named font file.',
          inspectFields: ['resultType', 'outputMode', 'performedSplit', 'usedFallback', 'warnings', 'manifestPath'],
          successCriteria: 'manifestPath exists and any fallback/copy-original result has been disclosed.',
        },
        {
          id: 'audit-single-output',
          templateId: 'output-audit-compact',
          required: true,
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Audit the single-font output directory when reporting generated files.',
          inspectFields: [...OUTPUT_AUDIT_SUMMARY_INSPECT_FIELDS],
          successCriteria: 'outputRoleDecision.auditAppliesToThisDirectory is not false, outputStructureDecision.status is pass, and structureSummary.conforms is true, or any structure limitation is disclosed.',
        },
      ],
      decisionPoints: [
        {
          id: 'fallback-result',
          when: 'resultType is single-woff2-* or copy-original-small-glyph.',
          action: 'Tell the user this was not a normal multi-subset split.',
          inspectFields: ['resultType', 'outputMode', 'usedFallback', 'warnings'],
          successCriteria: 'Fallback or copy-original behavior has been explicitly disclosed before treating the single-font run as complete.',
        },
      ],
    },
    batch: {
      id: 'batch-workflow',
      summary: 'Preflight source inputs, optionally resolve layout mismatch, preview batch output, write reviewed output, then audit structure.',
      orderedSteps: [
        {
          id: 'source-preflight',
          templateId: 'source-preflight-compact',
          required: true,
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Understand source size, ignored files, invalid fonts, and scan truncation before batch processing.',
          inspectFields: sourcePreflightInspectFields(['invalidFontCount', 'missingIdentityCount']),
          successCriteria: 'The source scan is complete enough for the requested batch scope.',
        },
        {
          id: 'layout-decision',
          templateId: 'directory-mismatch-plan',
          required: 'when-layout-is-not-obviously-compatible',
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Check whether source directory layout matches desired family grouping.',
          inspectFields: withDirectoryRouteInspectFields(['sourceSafetyDecision', 'layout']),
          successCriteria: 'The grouping strategy is chosen and any layout warnings are reviewed.',
        },
        {
          id: 'batch-preview',
          templateId: 'batch-dry-run-preview',
          required: true,
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Preview selected fonts, dedupe, naming, skip decisions, and warnings.',
          inspectFields: ['sourceSafetyDecision', 'safetySummary', 'batchPolicySummary', 'dryRun', 'batchDecision', 'planned', 'batchWarnings', 'dedupeDecisionSummary', 'skippedDuplicates', 'errorCount', 'errors'],
          successCriteria: 'The preview paths, warnings, and dedupe policy match the user intent.',
        },
        {
          id: 'reviewed-write',
          templateId: 'batch-process-reviewed-plan',
          required: 'after-preview-review',
          writesFiles: true,
          sourceDestructive: false,
          goal: 'Run the reviewed batch write.',
          inspectFields: ['sourceSafetyDecision', 'safetySummary', 'batchPolicySummary', 'batchDecision', 'batchWarnings', 'dedupeDecisionSummary', 'errorCount', 'errors', 'recommendedNextActions'],
          successCriteria: 'errorCount is zero and output audit is available.',
        },
        auditStep,
      ],
      decisionPoints: [
        {
          id: 'preserve-all-files',
          when: 'The user requires every supported source font file to be preserved even if duplicates appear equivalent.',
          action: 'Use workflowPreset preserve-all or explicitly set batchDedupeMode none before previewing.',
          inspectFields: ['batchDedupeMode', 'dedupeDecisionSummary', 'batchDecision', 'planned', 'skippedDuplicates'],
          successCriteria: 'The following preview/write intentionally uses batchDedupeMode none or preserve-all, and skippedDuplicates reflects the preserve-all intent.',
        },
      ],
    },
    inspect: {
      id: 'inspection-workflow',
      summary: 'Use read-only tools to verify source inputs or generated output, increasing maxFiles when scans are truncated.',
      orderedSteps: [
        {
          id: 'source-preflight',
          templateId: 'source-preflight-compact',
          required: 'when-inspecting-source-fonts',
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Inspect source font inputs without writing output.',
          inspectFields: sourcePreflightInspectFields(),
          successCriteria: 'maxFilesHit is false, or truncation is disclosed.',
        },
        auditStep,
      ],
      decisionPoints: [
        {
          id: 'need-details',
          when: 'A compact scan shows warnings, missing manifests, invalid fonts, or structure issues.',
          action: 'Rerun with includeFiles:true or includeFamilies:true only for the narrowed area that needs detail.',
          inspectFields: [...OUTPUT_AUDIT_DETAIL_INSPECT_FIELDS],
          successCriteria: 'Detailed rerun is limited to the narrowed area and resolves or discloses the warnings, missing manifests, invalid fonts, or structure issues that prompted it.',
        },
      ],
    },
    organize: {
      id: 'organization-workflow',
      summary: 'Plan directory cleanup with a dry run, copy to a staging directory only after review, then inspect or batch-preview that staged directory.',
      orderedSteps: [
        {
          id: 'organization-plan',
          templateId: 'directory-mismatch-plan',
          required: true,
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Plan source grouping and copy actions without writing.',
          inspectFields: withDirectoryRouteInspectFields(['sourceSafetyDecision', 'safetySummary', 'batchPolicySummary', 'layout', 'plan']),
          successCriteria: 'The copy plan and grouping policy are acceptable.',
        },
        {
          id: 'copy-staging',
          templateId: 'copy-organized-staging',
          required: 'only-if-user-wants-staging',
          writesFiles: true,
          sourceDestructive: false,
          goal: 'Copy selected fonts into outputDir without moving or deleting source files.',
          inspectFields: withDirectoryRouteInspectFields(['sourceSafetyDecision', 'safetySummary', 'batchPolicySummary', 'copiedCount', 'organizationManifestPath']),
          successCriteria: 'sourceDestructive is false and copiedCount/organizationWarnings match the reviewed plan.',
        },
        {
          id: 'inspect-staging',
          templateId: 'source-preflight-compact',
          required: 'after-copy-staging',
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Inspect the staging output as the next source directory.',
          inspectFields: sourcePreflightInspectFields(),
          successCriteria: 'The staging directory contains the expected supported fonts.',
        },
        {
          id: 'preview-next-batch',
          templateId: 'batch-dry-run-preview',
          required: 'before-splitting-staging-or-original-source',
          writesFiles: false,
          sourceDestructive: false,
          goal: 'Preview split output using either recommendedBatchPreviewArgs or the staged outputDir.',
          inspectFields: ['sourceSafetyDecision', 'safetySummary', 'batchPolicySummary', 'batchDecision', 'planned', 'batchWarnings', 'dedupeDecisionSummary', 'skippedDuplicates'],
          successCriteria: 'The batch preview matches the selected grouping and dedupe policy.',
        },
      ],
      decisionPoints: [
        {
          id: 'copy-not-needed',
          when: 'The user only wants split output and recommendedBatchPreviewArgs are acceptable.',
          action: 'Skip copy-organized-staging and run split_font_batch safe-preview on the original inputDir.',
          inspectFields: withDirectoryRouteInspectFields(['layout']),
          successCriteria: 'Skipping staging is intentional, and recommendedBatchPreviewArgs plus layout/organization warnings support direct original-input preview.',
        },
      ],
    },
  };
  return plans[workflow] || plans.overview;
}
